script:
 — "bundle exec rake neo4j:install['community-2.2.0-M02'] neo4j:start default --trace"
 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: master
